### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DanielLiCodes**

### CODE REVIEW

**Comment by Nifury** [comment]
Thanks for the PR!
Two minor issues:
1. webpack-cli 4.9 is not compatible with cli/serve 1.7. We might need to update webpack-cli to 4.10. See https://github.com/webpack/webpack-cli/issues/3294
2. It seems that the call graph is only rendered on the top half of the webpage.

image

**Comment by DanielLiCodes** [comment]
Fixed the height issue, but still haven't tried updating regarding the webpack-cli. Will check that out next!

**Comment by DanielLiCodes** [comment]
Updated to webpack cli 4.10, and everything works fine on my end! Please let me know if there is anything else to change.

**Comment by Nifury** [comment]
Thanks!

**Pull request merged**
